title: Molly's Blog
author: Molly
email: mollymann02@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog! 
# social links
twitter_username: molly_bl00m
github_username:  mollymann02

show_excerpts: true # set to false to remove excerpts on the homepage
